# Generated by Django 3.2.8 on 2021-11-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('work_email', models.CharField(max_length=100)),
                ('personal_email', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('employee_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('employment_date', models.DateTimeField(auto_now_add=True)),
                ('insurance_number', models.CharField(max_length=100)),
                ('tax_pin_number', models.CharField(max_length=100)),
                ('paye', models.DecimalField(decimal_places=2, max_digits=40)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=40)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=40)),
                ('tax_deducted', models.DecimalField(decimal_places=2, max_digits=40)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=40)),
                ('pension', models.DecimalField(decimal_places=2, max_digits=40)),
                ('sacco', models.DecimalField(decimal_places=2, max_digits=40)),
                ('medical_cover', models.DecimalField(decimal_places=2, max_digits=40)),
            ],
        ),
    ]
