# Generated by Django 3.2.8 on 2021-11-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=30)),
                ('payment_type', models.CharField(choices=[('MOBILE', 'mobile'), ('BANK', 'bank account')], default='', max_length=20)),
            ],
        ),
    ]
