# Generated by Django 3.2.8 on 2021-11-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
