# Generated by Django 3.2.8 on 2021-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('merchant', models.CharField(default='MERCHANTS', max_length=100)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('approved_expenses', models.IntegerField(default='0')),
                ('total_amount', models.DecimalField(decimal_places=2, default='0', max_digits=40)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
